/**
 * Pre-computed demo data — generated by runKernelDemo() with seed=42.
 * Deterministic: identical inputs always produce identical outputs.
 * This file eliminates kernel imports from the web app render path.
 */

import type { KernelDemoResult } from "./demo-types";

export const demoData: KernelDemoResult = {
  "seed": 42,
  "baseTime": 1700000000000,
  "events": [
    {
      "eventId": "9972daab-2c86-459f-9d78-3fe1be4e3280",
      "eventType": "OrganizationCreated",
      "version": 1,
      "timestamp": 1700000000000,
      "streamId": "Organization#org-demo-001"
    },
    {
      "eventId": "af9c0078-d60d-4708-840f-2fc887062cd7",
      "eventType": "MemberAdded",
      "version": 2,
      "timestamp": 1700000001000,
      "streamId": "Organization#org-demo-001"
    },
    {
      "eventId": "7ccf5173-090d-4e98-bea5-354dbddb8234",
      "eventType": "MemberRoleGranted",
      "version": 3,
      "timestamp": 1700000002000,
      "streamId": "Organization#org-demo-001"
    }
  ],
  "determinism": {
    "seed": 42,
    "run1": [
      "9972daab-2c86-459f-9d78-3fe1be4e3280",
      "af9c0078-d60d-4708-840f-2fc887062cd7",
      "7ccf5173-090d-4e98-bea5-354dbddb8234"
    ],
    "run2": [
      "9972daab-2c86-459f-9d78-3fe1be4e3280",
      "af9c0078-d60d-4708-840f-2fc887062cd7",
      "7ccf5173-090d-4e98-bea5-354dbddb8234"
    ],
    "identical": true
  },
  "projection": {
    "name": "Event Counter",
    "state": {
      "OrganizationCreated": 1,
      "MemberAdded": 1,
      "MemberRoleGranted": 1
    }
  },
  "decision": {
    "decisionId": "dec#e6ccad32",
    "outcome": "deny",
    "rationale": "Evaluated 1 active policy(ies); 1 matched (rules: [demo.rule.priority-lt-5]); deny-wins outcome 'deny'. [evaluator v1]",
    "matchedRules": [
      "demo.rule.priority-lt-5"
    ],
    "evaluatedAt": 1700000000000,
    "inputHash": "f8657c3a",
    "sourceEventCount": 3
  },
  "extension": {
    "plugins": [
      {
        "id": "opsos.protocol.demo",
        "version": "0.1.0",
        "name": "Demo Protocol"
      }
    ],
    "registrationKinds": [
      {
        "kind": "capability",
        "count": 1
      },
      {
        "kind": "intent-type",
        "count": 1
      },
      {
        "kind": "analytics",
        "count": 1
      }
    ]
  },
  "compiler": {
    "intentType": "demo.run",
    "ok": true,
    "stageCount": 9,
    "stages": [
      {
        "name": "kernel.normalizer",
        "phase": "normalize",
        "order": 10,
        "ran": true,
        "durationMs": 0
      },
      {
        "name": "kernel.validator",
        "phase": "validate",
        "order": 10,
        "ran": true,
        "durationMs": 0
      },
      {
        "name": "kernel.policy-evaluator",
        "phase": "evaluate",
        "order": 10,
        "ran": true,
        "durationMs": 0
      },
      {
        "name": "kernel.capability-resolver",
        "phase": "resolve",
        "order": 10,
        "ran": true,
        "durationMs": 0
      },
      {
        "name": "kernel.planner",
        "phase": "plan",
        "order": 10,
        "ran": true,
        "durationMs": 0
      },
      {
        "name": "kernel.optimizer",
        "phase": "optimize",
        "order": 10,
        "ran": true,
        "durationMs": 0
      },
      {
        "name": "kernel.scheduler",
        "phase": "schedule",
        "order": 10,
        "ran": true,
        "durationMs": 0
      },
      {
        "name": "kernel.router",
        "phase": "route",
        "order": 10,
        "ran": true,
        "durationMs": 0
      },
      {
        "name": "kernel.graph-builder",
        "phase": "finalize",
        "order": 10,
        "ran": true,
        "durationMs": 0
      }
    ],
    "graphId": "graph:intent-demo-001",
    "nodeCount": 1,
    "edgeCount": 0,
    "seed": 57911259,
    "planId": "plan:intent-demo-001",
    "taskCount": 1,
    "diagnostics": [
      {
        "severity": "info",
        "code": "POLICY_ALLOW",
        "message": "Evaluated 1 active policy(ies); 1 matched (rules: [compiler.rule.allow]); deny-wins outcome 'allow'. [evaluator v1]",
        "stage": "kernel.policy-evaluator"
      },
      {
        "severity": "info",
        "code": "DEMAND_DERIVED",
        "message": "Derived 1 demand from intent 'intent-demo-001'; 1 candidate capability(ies).",
        "stage": "kernel.capability-resolver"
      },
      {
        "severity": "info",
        "code": "PLAN_DRAFTED",
        "message": "Drafted plan 'plan:intent-demo-001' with 1 task(s).",
        "stage": "kernel.planner"
      },
      {
        "severity": "warn",
        "code": "SCHEDULE_UNMET",
        "message": "Scheduler 'noop' left 1/1 demand(s) unmet. noop-scheduler: no algorithm installed",
        "stage": "kernel.scheduler"
      },
      {
        "severity": "warn",
        "code": "ROUTES_EMPTY",
        "message": "No schedule slots available; tasks are unassigned. A protocol router stage is required for resource assignment.",
        "stage": "kernel.router"
      },
      {
        "severity": "info",
        "code": "GRAPH_BUILT",
        "message": "Built execution graph 'graph:intent-demo-001' with 1 node(s), 0 edge(s), seed=57911259.",
        "stage": "kernel.graph-builder"
      }
    ]
  },
  "protocolSdk": {
    "protocols": [
      {
        "id": "opsos.protocol.demo",
        "name": "demo",
        "displayName": "Demo Protocol",
        "version": "1.0.0",
        "state": "enabled",
        "installedAt": 1700000020000,
        "contributions": [
          {
            "kind": "capabilities",
            "count": 1
          },
          {
            "kind": "intentTypes",
            "count": 1
          },
          {
            "kind": "compilerStages",
            "count": 1
          },
          {
            "kind": "workflows",
            "count": 1
          },
          {
            "kind": "policies",
            "count": 1
          },
          {
            "kind": "rules",
            "count": 1
          },
          {
            "kind": "readModels",
            "count": 1
          }
        ],
        "validationErrors": 0,
        "validationWarnings": 0
      }
    ],
    "lifecycleEvents": [
      {
        "protocolId": "opsos.protocol.demo",
        "from": "uninstalled",
        "to": "discovered",
        "at": 1700000020000,
        "reason": "discovered"
      },
      {
        "protocolId": "opsos.protocol.demo",
        "from": "discovered",
        "to": "validated",
        "at": 1700000020000
      },
      {
        "protocolId": "opsos.protocol.demo",
        "from": "validated",
        "to": "installed",
        "at": 1700000020000
      },
      {
        "protocolId": "opsos.protocol.demo",
        "from": "installed",
        "to": "enabled",
        "at": 1700000020000
      }
    ],
    "capabilityCount": 1,
    "intentTypeCount": 1,
    "compilerExtensionCount": 1
  },
  "appRuntime": {
    "applications": [
      {
        "id": "eks-clean-demo",
        "name": "eks-clean-demo",
        "displayName": "Eks-Clean Demo",
        "status": "active",
        "protocolId": "opsos.protocol.demo",
        "protocolVersion": "1.0.0",
        "version": "1.0.0",
        "organizationId": "org-eks-group",
        "tenantId": "tenant-eks",
        "primaryDomain": "clean.eksgroup.demo",
        "pathPrefix": "/apps/eks-clean-demo",
        "theme": {
          "primary": "#0d9488",
          "accent": "#14b8a6",
          "mode": "light"
        },
        "logoUrl": "/logo.svg",
        "featureFlags": {
          "subscriptions": false,
          "marketplace": false,
          "aiRecommendations": true,
          "multiRegion": false
        },
        "navigationCount": 3,
        "localeCount": 2,
        "authProviderCount": 1,
        "uiExtensionCount": 2,
        "configFieldCount": 3,
        "versionHistoryCount": 1,
        "validationErrors": 0,
        "validationWarnings": 0
      }
    ],
    "installSteps": [
      {
        "step": "compatibility",
        "ok": true
      },
      {
        "step": "validate",
        "ok": true
      },
      {
        "step": "create",
        "ok": true
      },
      {
        "step": "install",
        "ok": true
      },
      {
        "step": "configure",
        "ok": true
      },
      {
        "step": "activate",
        "ok": true
      }
    ],
    "installOk": true,
    "resolvedConfig": {
      "defaultLocale": "en",
      "maxConcurrentJobs": 100,
      "aiRecommendations": true
    },
    "resolvedNavigation": [
      {
        "id": "dashboard",
        "label": "Dashboard",
        "order": 10
      },
      {
        "id": "operations",
        "label": "Operations",
        "order": 20
      },
      {
        "id": "analytics",
        "label": "Analytics",
        "order": 30
      }
    ],
    "resolvedAuthProviders": [
      "payswap"
    ],
    "resolvedDefaultLocale": "en"
  },
  "platformSnapshot": {
    "health": {
      "status": "healthy",
      "kernelVersion": "1.3.0",
      "apiVersion": "1.0.0",
      "protocolCount": 1,
      "applicationCount": 1,
      "activeApplicationCount": 1,
      "eventStorePosition": 3,
      "projectionCount": 1,
      "compilerStageCount": 10,
      "checks": [
        {
          "name": "event-store",
          "status": "healthy",
          "detail": "3 events"
        },
        {
          "name": "protocols",
          "status": "healthy",
          "detail": "1 installed"
        },
        {
          "name": "applications",
          "status": "healthy",
          "detail": "1 active"
        },
        {
          "name": "projections",
          "status": "healthy",
          "detail": "1 registered"
        },
        {
          "name": "compiler",
          "status": "healthy",
          "detail": "10 stages"
        }
      ]
    },
    "protocols": [
      {
        "id": "opsos.protocol.demo",
        "name": "demo",
        "displayName": "Demo Protocol",
        "version": "1.0.0",
        "state": "enabled",
        "installedAt": 1700000020000,
        "contributions": [
          {
            "kind": "capabilities",
            "count": 1
          },
          {
            "kind": "intentTypes",
            "count": 1
          },
          {
            "kind": "compilerStages",
            "count": 1
          },
          {
            "kind": "workflows",
            "count": 1
          },
          {
            "kind": "policies",
            "count": 1
          },
          {
            "kind": "rules",
            "count": 1
          },
          {
            "kind": "readModels",
            "count": 1
          }
        ],
        "validationErrors": 0,
        "validationWarnings": 0
      }
    ],
    "applications": [
      {
        "id": "eks-clean-demo",
        "name": "eks-clean-demo",
        "displayName": "Eks-Clean Demo",
        "status": "active",
        "protocolId": "opsos.protocol.demo",
        "protocolVersion": "1.0.0",
        "version": "1.0.0",
        "organizationId": "org-eks-group",
        "tenantId": "tenant-eks",
        "primaryDomain": "clean.eksgroup.demo",
        "pathPrefix": "/apps/eks-clean-demo",
        "theme": {
          "primary": "#0d9488",
          "accent": "#14b8a6",
          "mode": "light"
        },
        "logoUrl": "/logo.svg",
        "featureFlags": {
          "subscriptions": false,
          "marketplace": false,
          "aiRecommendations": true,
          "multiRegion": false
        },
        "navigationCount": 3,
        "localeCount": 2,
        "authProviderCount": 1,
        "uiExtensionCount": 2,
        "configFieldCount": 3,
        "versionHistoryCount": 1,
        "validationErrors": 0,
        "validationWarnings": 0
      }
    ],
    "organizations": [
      {
        "id": "org-eks-group",
        "name": "org-eks-group",
        "status": "active",
        "tenantId": "tenant-eks",
        "memberCount": 0,
        "applicationCount": 1
      }
    ],
    "capabilities": [
      {
        "id": "demo.cap.execute",
        "capabilityType": "demo.execute",
        "ownerProtocolId": "opsos.protocol.demo",
        "version": "1.0.0",
        "inputCount": 1,
        "outputCount": 1,
        "tags": [
          "demo",
          "self-test"
        ]
      }
    ],
    "intentTypes": [
      {
        "intentType": "demo.run",
        "ownerProtocolId": "opsos.protocol.demo",
        "version": "1.0.0",
        "requiredCapabilityCount": 1,
        "compilerHookCount": 0
      }
    ],
    "workflows": [
      {
        "id": "demo.workflow.run",
        "name": "Demo Run Workflow",
        "ownerProtocolId": "opsos.protocol.demo",
        "stageCount": 3,
        "triggerIntentTypes": [
          "demo.run"
        ]
      }
    ],
    "policies": [
      {
        "id": "demo.policy.verbose-allow",
        "name": "Demo Verbose Allow",
        "ownerProtocolId": "opsos.protocol.demo",
        "scope": "tenant",
        "effect": "allow",
        "priority": 50,
        "ruleCount": 1
      }
    ],
    "compilerExtensions": [
      {
        "name": "demo.planner-logger",
        "ownerProtocolId": "opsos.protocol.demo",
        "phase": "plan",
        "order": 20,
        "insertion": "after-kernel-phase"
      }
    ],
    "observability": {
      "eventCount": 3,
      "decisions": [],
      "metricPoints": [],
      "spanCount": 0,
      "auditEvents": []
    }
  },
  "coordination": {
    "outcome": "assigned",
    "steps": [
      {
        "step": "match",
        "detail": "match: 1 candidate(s) \u2192 selected resource-R",
        "ok": true
      },
      {
        "step": "reserve",
        "detail": "reservation: resv#resource-R#1700000040000#1 (commitmentId=cmmt#resv#resource-R#1700000040000#1#1700000040000#2)",
        "ok": true
      },
      {
        "step": "commit",
        "detail": "commitment: cmmt#resv#resource-R#1700000040000#1#1700000040000#2 (status=active)",
        "ok": true
      },
      {
        "step": "assign",
        "detail": "assignment: asgn#task-coord-1#1700000040000#1 (status=pending)",
        "ok": true
      },
      {
        "step": "accept",
        "detail": "assignment asgn#task-coord-1#1700000040000#1 \u2192 accepted",
        "ok": true
      }
    ],
    "matchResourceId": "resource-R",
    "matchScore": 0,
    "reservationId": "resv#resource-R#1700000040000#1",
    "commitmentId": "cmmt#resv#resource-R#1700000040000#1#1700000040000#2",
    "assignmentId": "asgn#task-coord-1#1700000040000#1",
    "assignmentStatus": "accepted",
    "candidateCount": 1
  },
  "resourceKernel": {
    "resources": [
      {
        "id": "resource-R1",
        "resourceType": "generic",
        "displayName": "Resource R1 (primary)",
        "operationalState": "idle",
        "healthScore": 0.95,
        "reliabilityScore": 0.98,
        "location": "Zone A",
        "certificationCount": 1,
        "capacityMax": 10,
        "capacityRemaining": 10,
        "twinUpdatedAt": 1700000040000
      },
      {
        "id": "resource-R2",
        "resourceType": "generic",
        "displayName": "Resource R2 (backup)",
        "operationalState": "idle",
        "healthScore": 0.8,
        "reliabilityScore": 0.85,
        "certificationCount": 0,
        "capacityMax": 5,
        "capacityRemaining": 5,
        "twinUpdatedAt": 1700000040000
      }
    ],
    "capableResults": [],
    "queryCapabilityType": "generic.execute"
  },
  "knowledgeKernel": {
    "items": [
      {
        "id": "ki-proc-generic-execute",
        "kind": "procedure",
        "title": "Generic Execution Procedure",
        "version": 1,
        "status": "active",
        "confidence": 0.92,
        "tags": [
          "generic",
          "execution"
        ],
        "evidenceCount": 1,
        "ownerProtocolId": "opsos.protocol.demo"
      },
      {
        "id": "ki-reg-generic-compliance",
        "kind": "regulation",
        "title": "Generic Compliance Regulation",
        "version": 1,
        "status": "active",
        "confidence": 1,
        "tags": [
          "compliance"
        ],
        "evidenceCount": 0
      },
      {
        "id": "ki-fact-generic",
        "kind": "fact",
        "title": "Generic Resource Capability Fact",
        "version": 1,
        "status": "active",
        "confidence": 0.88,
        "tags": [
          "capability"
        ],
        "evidenceCount": 0
      }
    ],
    "query": {
      "subjectKind": "resource",
      "subjectId": "resource-R1",
      "matchedItems": 3,
      "matchedProcedures": 1,
      "matchedRegulations": 1,
      "matchedFacts": 1,
      "complianceCompliant": false,
      "complianceViolations": 2
    }
  },
  "domainModeling": {
    "domainId": "opsos.domain.generic-operations",
    "domainName": "generic-operations",
    "version": 1,
    "entityTypeCount": 3,
    "relationshipCount": 2,
    "stateMachineCount": 2,
    "measurementCount": 1,
    "constraintCount": 1,
    "entityTypes": [
      {
        "id": "asset",
        "name": "Asset",
        "attributeCount": 2,
        "relationshipCount": 1,
        "twinEnabled": true,
        "hasStateMachine": true
      },
      {
        "id": "area",
        "name": "Area",
        "attributeCount": 2,
        "relationshipCount": 0,
        "twinEnabled": true,
        "hasStateMachine": false
      },
      {
        "id": "work-unit",
        "name": "WorkUnit",
        "attributeCount": 2,
        "relationshipCount": 1,
        "twinEnabled": false,
        "hasStateMachine": true
      }
    ],
    "relationships": [
      {
        "id": "asset-contains-area",
        "name": "contains",
        "kind": "contains",
        "source": "asset",
        "target": "area",
        "cardinality": "one-to-many"
      },
      {
        "id": "work-unit-requires-capability",
        "name": "requires",
        "kind": "requires",
        "source": "work-unit",
        "target": "asset",
        "cardinality": "many-to-many"
      }
    ]
  },
  "composition": {
    "packageId": "opsos.protocol.demo",
    "version": "1.0.0",
    "compiled": true,
    "stages": [
      {
        "stage": "resolve",
        "ok": true
      },
      {
        "stage": "validate",
        "ok": true
      },
      {
        "stage": "link",
        "ok": true
      },
      {
        "stage": "bundle",
        "ok": true
      },
      {
        "stage": "sign",
        "ok": true
      },
      {
        "stage": "package",
        "ok": true
      }
    ],
    "digest": "986e3917571d7eef",
    "signed": true,
    "installed": true,
    "activated": true,
    "lifecycleEvents": [
      {
        "from": "installed",
        "to": "activated"
      }
    ],
    "contentCounts": [
      {
        "kind": "domainBindings",
        "count": 3
      },
      {
        "kind": "knowledgeRefs",
        "count": 3
      },
      {
        "kind": "compilerExtensions",
        "count": 1
      },
      {
        "kind": "policies",
        "count": 1
      },
      {
        "kind": "capabilities",
        "count": 1
      },
      {
        "kind": "workflows",
        "count": 1
      }
    ]
  },
  "conformance": {
    "totalScenarios": 25,
    "passed": 25,
    "failed": 0,
    "deterministicChecksum": "095ee579",
    "replayVerified": true,
    "scenarios": [
      {
        "id": "single-resource-match",
        "name": "Single Resource Match",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 5,
        "durationMs": 9
      },
      {
        "id": "multi-resource-match",
        "name": "Multi Resource Match",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 5,
        "durationMs": 11
      },
      {
        "id": "resource-unavailable",
        "name": "Resource Unavailable",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "conflicting-commitments",
        "name": "Conflicting Commitments",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 6,
        "durationMs": 11
      },
      {
        "id": "policy-denial",
        "name": "Policy Denial",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 1,
        "durationMs": 4
      },
      {
        "id": "policy-allow",
        "name": "Policy Allow",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 5,
        "durationMs": 10
      },
      {
        "id": "timeout-escalation",
        "name": " Timeout Escalation",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "reassignment",
        "name": "Reassignment",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "rollback",
        "name": "Rollback",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "degraded-resource",
        "name": "Degraded Resource",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 5,
        "durationMs": 9
      },
      {
        "id": "missing-capability",
        "name": "Missing Capability",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 2,
        "durationMs": 6
      },
      {
        "id": "capacity-exhaustion",
        "name": "Capacity Exhaustion",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "expired-reservation",
        "name": "Expired Reservation",
        "category": "error",
        "passed": true,
        "assertionsPassed": 3,
        "assertionsTotal": 3,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "stale-knowledge",
        "name": "Stale Knowledge",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 6,
        "durationMs": 12
      },
      {
        "id": "compiler-failure",
        "name": "Compiler Failure",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 1,
        "durationMs": 4
      },
      {
        "id": "package-incompatibility",
        "name": "Package Incompatibility",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 1,
        "durationMs": 4
      },
      {
        "id": "extension-failure",
        "name": "Extension Failure",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 1,
        "durationMs": 4
      },
      {
        "id": "network-partition",
        "name": "Network Partition",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "priority-queue",
        "name": "Priority Queue",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 4,
        "durationMs": 10
      },
      {
        "id": "weighted-queue",
        "name": "Weighted Queue",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 4,
        "durationMs": 10
      },
      {
        "id": "deadline-queue",
        "name": "Deadline Queue",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 4,
        "durationMs": 10
      },
      {
        "id": "negotiation-timeout",
        "name": "Negotiation Timeout",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 6,
        "durationMs": 10
      },
      {
        "id": "escalation-trigger",
        "name": "Escalation Trigger",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "transfer-provenance",
        "name": "Transfer Provenance",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 8
      },
      {
        "id": "twin-update",
        "name": "Twin Update",
        "category": "error",
        "passed": true,
        "assertionsPassed": 4,
        "assertionsTotal": 4,
        "replayVerified": true,
        "eventCount": 3,
        "durationMs": 7
      }
    ]
  },
  "intelligence": {
    "graphNodeCount": 8,
    "graphEdgeCount": 7,
    "explanation": {
      "kind": "compiler-decision",
      "rationale": "Compiler decision for task 'task-coord-1' at stage 'graph-build': the node was admitted because it satisfied the stage's structural and semantic invariants.",
      "confidence": 0.7500000000000001,
      "evidenceCount": 3,
      "alternativeCount": 1
    },
    "recommendations": [
      {
        "category": "optimization",
        "action": "No actionable signals detected \u2014 review the operational baseline periodically.",
        "confidence": 0.4,
        "impact": "low"
      }
    ],
    "predictions": [
      {
        "metric": "execution-duration",
        "value": 0,
        "confidence": 0.2,
        "method": "moving-average(n=0)"
      },
      {
        "metric": "queue-growth",
        "value": 0,
        "confidence": 0.2,
        "method": "linear-extrapolation(n=0, interval=60000ms)"
      },
      {
        "metric": "resource-utilization",
        "value": 0.5,
        "confidence": 0.2,
        "method": "passthrough(utilization)"
      }
    ],
    "anomalies": [],
    "learningSignals": 1,
    "aiContracts": [
      "Reasoner",
      "Planner",
      "Predictor",
      "Recommender",
      "Optimizer",
      "Evaluator",
      "MemoryProvider"
    ]
  },
  "governance": {
    "versions": [
      {
        "id": "opsos.kernel",
        "kind": "kernel",
        "version": "1.0.0",
        "lifecycle": "stable"
      },
      {
        "id": "opsos.kernel",
        "kind": "kernel",
        "version": "1.2.0",
        "lifecycle": "stable"
      },
      {
        "id": "opsos.protocol.demo",
        "kind": "package",
        "version": "1.0.0",
        "lifecycle": "stable"
      },
      {
        "id": "opsos.domain.generic-operations",
        "kind": "domain",
        "version": "1",
        "lifecycle": "stable"
      }
    ],
    "compatibilityResults": [
      {
        "dimension": "protocol-kernel",
        "compatible": true,
        "details": "[protocol-kernel] 1.0.0 \u2194 1.2.0 major=ok minor=ok range=none-declared"
      },
      {
        "dimension": "package-application",
        "compatible": true,
        "details": "[package-application] 1.0.0 \u2194 1.0.0 major=ok minor=ok range=none-declared"
      }
    ],
    "certifications": [
      {
        "kind": "protocol-certified",
        "subjectId": "opsos.protocol.demo",
        "status": "certified"
      }
    ],
    "migrationPlan": {
      "type": "upgrade",
      "from": "1.0.0",
      "to": "1.2.0",
      "stepCount": 6,
      "dryRunOk": true
    },
    "policies": [
      {
        "kind": "breaking-changes",
        "enforcement": "blocking"
      },
      {
        "kind": "protocol-certification",
        "enforcement": "required"
      }
    ],
    "lifecycleStates": [
      "experimental",
      "preview",
      "stable",
      "deprecated",
      "retired"
    ]
  },
  "platform": {
    "aiWorkforce": {
      "agentCount": 1,
      "teamCount": 0,
      "roleCount": 5,
      "pendingApprovals": 1,
      "handoffs": 0,
      "memories": 1
    },
    "communication": {
      "channelCount": 1,
      "templateCount": 1,
      "recipientCount": 1,
      "notificationsDispatched": 1,
      "suppressedChannels": 0
    },
    "workflow": {
      "definitionCount": 1,
      "instanceCount": 1,
      "activeInstances": 0,
      "completedInstances": 0,
      "timersScheduled": 1,
      "recurringJobs": 0
    },
    "integration": {
      "connectorCount": 2,
      "capabilityCount": 1,
      "webhookEndpoints": 0,
      "syncJobs": 0,
      "paymentProvider": "payswap"
    },
    "twinRuntime": {
      "twinCount": 1,
      "telemetryReadings": 2,
      "predictions": 1,
      "simulations": 1,
      "recommendations": 0,
      "healthIssues": 0
    },
    "experience": {
      "sessionCount": 1,
      "journeyCount": 0,
      "intentCount": 1,
      "milestonesTracked": 0,
      "goals": 1,
      "guidanceGenerated": 0
    }
  },
  "modules": [
    {
      "name": "shared-kernel",
      "layer": "Foundation",
      "dependsOn": "\u2014",
      "description": "19 canonical primitives (frozen v1), branded IDs, Result/Option, value objects, RuntimeClock & RandomSource ports."
    },
    {
      "name": "events",
      "layer": "Foundation",
      "dependsOn": "shared-kernel",
      "description": "EventEnvelope, EventStore (optimistic concurrency), SnapshotStore, EventSourcedRepository."
    },
    {
      "name": "observability",
      "layer": "Foundation",
      "dependsOn": "shared-kernel",
      "description": "Tracer, Meter, Logger, AuditSink, ProvenanceRecorder ports + Noop/InMemory adapters."
    },
    {
      "name": "config",
      "layer": "Foundation",
      "dependsOn": "shared-kernel",
      "description": "ConfigSource, ConfigRegistry (precedence merge), Secrets ports + in-memory/env adapters."
    },
    {
      "name": "runtime",
      "layer": "Engine",
      "dependsOn": "shared-kernel, events, observability, config",
      "description": "RuntimeClock impls, SeededRandomSource, ExecutionContext, ExecutionGraph, DeterministicRuntimeExecutor."
    },
    {
      "name": "identity",
      "layer": "Context",
      "dependsOn": "shared-kernel, events, observability",
      "description": "User (event-sourced), Principal, Role, Permission, Credential, IdentityProvider & Authenticator ports."
    },
    {
      "name": "organizations",
      "layer": "Context",
      "dependsOn": "shared-kernel, events, identity",
      "description": "Organization, Tenant, Membership aggregates. Tenancy isolation boundary."
    },
    {
      "name": "projections",
      "layer": "Read side",
      "dependsOn": "shared-kernel, events, runtime",
      "description": "ProjectionDefinition, ProjectionEngine, ProjectionStore. Pure (event,state)\u2192state read models."
    },
    {
      "name": "policy",
      "layer": "Governance",
      "dependsOn": "shared-kernel, events, runtime",
      "description": "PredicateSpec evaluator, PolicyDefinition, Rule, PolicyEngine, Decision with provenance."
    },
    {
      "name": "scheduling",
      "layer": "Foundation",
      "dependsOn": "shared-kernel, events, runtime",
      "description": "Schedule, ScheduleSlot, Scheduler PORT + NoopScheduler. No algorithm (ADR-0008)."
    },
    {
      "name": "extension",
      "layer": "Host",
      "dependsOn": "shared-kernel",
      "description": "Plugin, ExtensionHost, ExtensionRegistry, 9 registration contracts. Protocol host only (ADR-0006)."
    },
    {
      "name": "compiler",
      "layer": "Compiler",
      "dependsOn": "shared-kernel, runtime, policy, scheduling, extension",
      "description": "Intent \u2192 ExecutionGraph. 9-stage replaceable pipeline (ADR-0011). The ONLY component that creates work."
    },
    {
      "name": "protocol-sdk",
      "layer": "SDK",
      "dependsOn": "@kernel/api/v1",
      "description": "Protocol SDK: defineProtocol(), manifest validation, lifecycle manager, 14 contribution registries, DSL. Protocols describe, never execute (ADR-0012)."
    },
    {
      "name": "application-runtime",
      "layer": "Runtime",
      "dependsOn": "@kernel/api/v1, protocol-sdk",
      "description": "Application Runtime: installs branded, tenant-aware application instances of protocols. One protocol \u2192 many apps (ADR-0013)."
    },
    {
      "name": "control-plane",
      "layer": "Control",
      "dependsOn": "@kernel/api/v1",
      "description": "Platform Control Plane: read-only admin surface. Aggregates a PlatformSnapshot from all registries (ADR-0014)."
    },
    {
      "name": "coordination",
      "layer": "Coordination",
      "dependsOn": "shared-kernel",
      "description": "Coordination Kernel: matching/negotiation/reservation/commitment/assignment/queue/transfer/escalation engines. Marketplace is one strategy (ADR-0015)."
    },
    {
      "name": "resource-kernel",
      "layer": "Resource",
      "dependsOn": "shared-kernel",
      "description": "Resource Kernel: universal resource concepts \u2014 state, availability, capacity, location, calendar, skills, twin, maintenance, quality. Coordination queries it (ADR-0016)."
    },
    {
      "name": "knowledge-kernel",
      "layer": "Knowledge",
      "dependsOn": "shared-kernel",
      "description": "Knowledge Kernel: universal operational knowledge \u2014 SOPs, regulations, standards, facts, procedures, ontologies. Protocols register, kernel owns (ADR-0017)."
    },
    {
      "name": "domain-modeling",
      "layer": "Domain",
      "dependsOn": "shared-kernel, knowledge-kernel",
      "description": "Domain Modeling Framework: semantic layer \u2014 entity types, relationships, state machines, measurements, constraints. Domain \u2260 Protocol (ADR-0018)."
    },
    {
      "name": "composition",
      "layer": "Packaging",
      "dependsOn": "shared-kernel, protocol-sdk, domain-modeling",
      "description": "Composition & Operational Package System: turns protocol source into immutable .opspkg. Apps install packages (ADR-0019)."
    },
    {
      "name": "conformance",
      "layer": "Conformance",
      "dependsOn": "shared-kernel",
      "description": "Kernel Conformance & Simulation Framework: 25 generic scenarios validating kernel neutrality. Every protocol must pass (ADR-0020)."
    },
    {
      "name": "intelligence",
      "layer": "Intelligence",
      "dependsOn": "shared-kernel",
      "description": "Operational Intelligence Framework: observes, explains, predicts, recommends. Never performs work. AI providers implement contracts (ADR-0021)."
    },
    {
      "name": "governance",
      "layer": "Governance",
      "dependsOn": "shared-kernel",
      "description": "Platform Governance & Evolution: version compatibility, migration, lifecycle, certification, policies. Governs how the platform evolves (ADR-0022)."
    },
    {
      "name": "ai-workforce",
      "layer": "Platform",
      "dependsOn": "shared-kernel",
      "description": "AI Workforce Runtime: AI Org, Roles, Teams, Director, Agent lifecycle/memory/collaboration/handoffs, Human approval, Autonomous boundaries (M14)."
    },
    {
      "name": "communication",
      "layer": "Platform",
      "dependsOn": "shared-kernel",
      "description": "Communication Runtime: notifications, email, SMS, push, WhatsApp, voice, webhooks. Protocols publish events; platform decides delivery (M15)."
    },
    {
      "name": "workflow-runtime",
      "layer": "Platform",
      "dependsOn": "shared-kernel",
      "description": "Workflow Runtime: BPMN-like execution, waiting, retries, timers, approvals, compensation, saga, recurring jobs (M16)."
    },
    {
      "name": "integration-hub",
      "layer": "Platform",
      "dependsOn": "shared-kernel",
      "description": "Integration Hub: universal connectors \u2014 calendars, payments (PaySwap only), maps, identity, ERP, CRM, IoT, AI (M17)."
    },
    {
      "name": "twin-runtime",
      "layer": "Platform",
      "dependsOn": "shared-kernel",
      "description": "Digital Twin Runtime: current/historical/predicted/simulated state, live telemetry, health, recommendations (M18)."
    },
    {
      "name": "experience-runtime",
      "layer": "Platform",
      "dependsOn": "shared-kernel",
      "description": "Experience Runtime: Intent, Journey, Session, Context, Narrative, Guidance, Milestones, Goals. Apps expose experiences (M19)."
    },
    {
      "name": "api/v1",
      "layer": "Surface",
      "dependsOn": "all modules (facade)",
      "description": "Frozen versioned public API (ADR-0009). Everything outside the kernel imports from here."
    }
  ],
  "primitives": [
    {
      "name": "Intent",
      "owner": "runtime"
    },
    {
      "name": "Demand",
      "owner": "runtime"
    },
    {
      "name": "Task",
      "owner": "runtime"
    },
    {
      "name": "ExecutionPlan",
      "owner": "runtime"
    },
    {
      "name": "Execution",
      "owner": "runtime"
    },
    {
      "name": "Capability",
      "owner": "runtime"
    },
    {
      "name": "Resource",
      "owner": "runtime"
    },
    {
      "name": "Workflow",
      "owner": "runtime"
    },
    {
      "name": "Policy",
      "owner": "policy"
    },
    {
      "name": "Rule",
      "owner": "policy"
    },
    {
      "name": "Decision",
      "owner": "policy"
    },
    {
      "name": "Event",
      "owner": "events"
    },
    {
      "name": "Projection",
      "owner": "projections"
    },
    {
      "name": "Recommendation",
      "owner": "runtime"
    },
    {
      "name": "Route",
      "owner": "scheduling"
    },
    {
      "name": "Schedule",
      "owner": "scheduling"
    },
    {
      "name": "Simulation",
      "owner": "runtime"
    },
    {
      "name": "Observation",
      "owner": "runtime"
    },
    {
      "name": "Twin",
      "owner": "runtime"
    }
  ]
};
